name: home-assistant

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=America/New_York
    networks:
      homeassistant:
      lanvlan:
        ipv4_address: 192.168.1.11
    privileged: true
    # security_opt:
    #   - label:disable
    volumes:
      - /Apps/homeassistant:/config:Z
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: always
networks:
  homeassistant:
    name: homeassistant
    driver_opts:
      com.docker.network.bridge.name: br-ha
    ipam:
      config:
        - subnet: 172.21.1.0/24
          ip_range: 172.21.1.0/24
  lanvlan:
    name: lanvlan
    external: true
