name: home-assistant

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=America/New_York
    networks:
      homeassistant:
      ai:
      lanvlan:
        ipv4_address: 192.168.1.11
    privileged: true
    # security_opt:
    #   - label:disable
    volumes:
      - /Apps/homeassistant:/config:Z
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/serial/by-id/usb-zigbee_dongle
    restart: always
  zwavejs:
    image: zwavejs/zwave-js-ui:latest
    container_name: zwavejs
    environment:
      - TZ=America/New_York
    networks:
      - homeassistant
    #ports:
    #  - 8091:8091
    volumes:
      - /Apps/zwavejs:/usr/src/app/store:Z
    devices:
      - /dev/serial/by-id/usb-zwave_dongle:/dev/zwave
    restart: always
networks:
  homeassistant:
    name: homeassistant
    external: true
  ai:
    name: ai
    external: true
  lanvlan:
    name: lanvlan
    external: true
