name: nextcloud

services:
  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    environment:
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    networks:
      - nextcloud
    volumes:
      - /Apps/nextcloud/db:/var/lib/mysql:Z
    command: --transaction-isolation=READ-COMMITTED
    restart: always
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    environment:
      - TZ=America/New_York
    networks:
      - nextcloud
    restart: always
  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    environment:
      - TZ=America/New_York
      - MYSQL_HOST=nextcloud-db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=server.lan nextcloud.myhome.duckdns.org
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=172.21.2.0/24
    networks:
      - nextcloud
    volumes:
      - /Apps/nextcloud/app:/var/www/html:z
      - /mnt/Tank/NextCloud:/var/www/html/data:z
    ports:
      - 10098:80
    depends_on:
      - nextcloud-redis
      - nextcloud-db
    restart: always
  nextcloud-cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    environment:
      - TZ=America/New_York
    entrypoint: /cron.sh
    networks:
      - nextcloud
    volumes:
      - /Apps/nextcloud/app:/var/www/html:z
      - /mnt/Tank/NextCloud:/var/www/html/data:z
    depends_on:
      - nextcloud-redis
      - nextcloud-db
    restart: always
networks:
  nextcloud:
    name: nextcloud
    driver_opts:
      com.docker.network.bridge.name: br-nextcloud
    ipam:
      config:
        - subnet: 172.21.2.0/24
          ip_range: 172.21.2.0/24
