name: portainer

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      - TZ=America/New_York
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Apps/portainer:/data:Z
    ports:
      - 9443:9443
    restart: always
