name: public-traffic

services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    environment:
      - TZ=America/New_York
    networks:
      - portainer
      - homeassistant
      - nextcloud
      - arr
      - ai
    volumes:
      - /Apps/nginx/data:/data:Z
      - /Apps/nginx/etc-letsencrypt:/etc/letsencrypt:Z
    ports:
      - 80:80
      - 443:443
      - 8181:81
    restart: always
networks:
  homeassistant:
    name: homeassistant
    driver_opts:
      com.docker.network.bridge.name: br-ha
    ipam:
      config:
        - subnet: 172.21.1.0/24
          ip_range:
            172.21.1.0/24
  nextcloud:
    name: nextcloud
    driver_opts:
      com.docker.network.bridge.name: br-nextcloud
    ipam:
      config:
        - subnet: 172.21.2.0/24
          ip_range: 172.21.2.0/24
  arr:
    name: arr
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: br-arr
    ipam:
      config:
        - subnet: 172.21.3.0/24
          ip_range: 172.21.3.0/24
        - subnet: fda6:80d8:cf96:1::/64
  ai:
    name: ai
    driver_opts:
      com.docker.network.bridge.name: br-ai
    ipam:
      config:
        - subnet: 172.21.4.0/24
          ip_range: 172.21.4.0/24
  portainer:
    name: portainer
    external: true
